// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ipfans/components/v2/lifecycle (interfaces: Lifecycle)
//
// Generated by this command:
//
//	mockgen -destination=./mocks/lifecycle/mock_lifecycle.go -package=lifecycle github.com/ipfans/components/v2/lifecycle Lifecycle
//

// Package lifecycle is a generated GoMock package.
package lifecycle

import (
	reflect "reflect"

	lifecycle "github.com/ipfans/components/v2/lifecycle"
	gomock "go.uber.org/mock/gomock"
)

// MockLifecycle is a mock of Lifecycle interface.
type MockLifecycle struct {
	ctrl     *gomock.Controller
	recorder *MockLifecycleMockRecorder
	isgomock struct{}
}

// MockLifecycleMockRecorder is the mock recorder for MockLifecycle.
type MockLifecycleMockRecorder struct {
	mock *MockLifecycle
}

// NewMockLifecycle creates a new mock instance.
func NewMockLifecycle(ctrl *gomock.Controller) *MockLifecycle {
	mock := &MockLifecycle{ctrl: ctrl}
	mock.recorder = &MockLifecycleMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLifecycle) EXPECT() *MockLifecycleMockRecorder {
	return m.recorder
}

// Append mocks base method.
func (m *MockLifecycle) Append(arg0 lifecycle.Hook) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Append", arg0)
}

// Append indicates an expected call of Append.
func (mr *MockLifecycleMockRecorder) Append(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Append", reflect.TypeOf((*MockLifecycle)(nil).Append), arg0)
}
